#!/bin/sh

OS=${OS:-unix}
OCAMLBUILD=ocamlbuild

DEPS=
case "$OS" in
unix) DEPS="lwt.unix" ;;
xen) DEPS="lwt" ;;
*) echo Unknown OS $OS; exit 1 ;;
esac

ocamlbuild -use-ocamlfind -pkgs $DEPS ${OS}/mirage-console.cma ${OS}/mirage-console.cmxa ${OS}/mirage-console.cmxs

B=_build/${OS}
if [ "$1" = "true" ]; then
  ocamlfind remove mirage-console || true
  ocamlfind install mirage-console ${OS}/META \
    $B/console.cmo $B/console.cmi $B/mirage-console.cma \
    $B/mirage-console.a $B/console.cmx $B/mirage-console.cmxa $B/mirage-console.cmxs
elif [ "$1" = "test" ]; then
  ocamlbuild -use-ocamlfind -pkgs mirage-types,$DEPS -I ${OS} lib_test/portable.cmo
fi
